### ISSUE TITLE
Catch exception on missing favicon

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/stadsarkiv-client#259]
Whenever stadsarkiv-client server-dev is called, the following exception stacktrace is thrown:

```
$ stadsarkiv-client server-dev
INFO:     Will watch for changes in these directories: ['C:\\Users\\azkb075']
INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
INFO:     Started reloader process [13652] using StatReload
2024-09-09 13:37:34,793 - env - DEBUG - Loaded .env-dist file
2024-09-09 13:37:34,793 - env - DEBUG - Local local\.env file NOT loaded
INFO:     Started server process [15620]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:56310 - "GET / HTTP/1.1" 200 OK
2024-09-09 13:37:39,589 - main - ERROR - 500 Error: http://localhost:5555/static/assets/favicon.ico?v=1.3.417
Traceback (most recent call last):
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\stadsarkiv_client\core\middleware.py", line 33, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\base.py", line 166, in call_next
    raise RuntimeError("No response returned.")
RuntimeError: No response returned.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\stadsarkiv_client\core\middleware.py", line 33, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\azkb075\.local\pipx\venvs\stadsarkiv-client\Lib\site-packages\starlette\middleware\base.py", line 166, in call_next
    raise RuntimeError("No response returned.")
RuntimeError: No response returned.
```

**Comment by diversen7** [comment]
Denne kan jeg ikke gengive. Kan du give mig `stadsarkiv-client` kommando hvor fejlen opstår?

Opgrader eventuelt til seneste: `pipx install git+https://github.com/aarhusstadsarkiv/stadsarkiv-client@v1.3.505 --force`

**Comment by diversen7** [comment]
Ah. Jeg kan se kommando i toppen: stadsarkiv-client server-dev

Men jeg kan ikke gengive.
