### ISSUE TITLE
Fix 500 error

### ISSUE THREAD

**Issue by diversen7** [aarhusstadsarkiv/stadsarkiv-client#268]
Should just be page not found
E.g. http://localhost:5555/HNAP1

**Comment by diversen7** [comment]
Should just be page not found. 

INFO:     127.0.0.1:46226 - "GET /HNAP1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/dennis/stadsarkiv-client/stadsarkiv_client/core/middleware.py", line 33, in dispatch
    response = await call_next(request)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starsessions/middleware.py", line 138, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starsessions/middleware.py", line 159, in __call__
    await self.app(scope, receive, send)
  File "/home/dennis/stadsarkiv-client/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/dennis/stadsarkiv-client/stadsarkiv_client/core/middleware.py", line 85, in dispatch
    response = await hooks.before_response(response)
  File "/home/dennis/stadsarkiv-client/./example-config-teater/hooks.py", line 181, in before_response
    if not hasattr(self.request.scope["endpoint"], "__name__"):
KeyError: 'endpoint'

**Comment by diversen7** [comment]
This is fixed in v1.3.507
